version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - /db/redis_vol:/data
      - /db/redis_vol/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - docker_network

  spring-app1:
    container_name: spring-app1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 8080:8080
    networks:
      - docker_network
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis

  spring-app2:
    container_name: spring-app2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 8081:8080
    networks:
      - docker_network
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis

networks:
  docker_network:
    external: true